locations = ["The Fairy Pools","Grand Canyon National Park","Huacachina", "Salar de Uyuni", "Plitvice Lakes National Park"]
console.log("original")
console.log(locations)
console.log("alphabeticalOrder")
alphabeticalOrder = locations.slice().sort()
console.log(alphabeticalOrder)
console.log("original")
console.log(locations)
console.log("reverseAlphabeticalOrder")
reverseAlphabeticalOrder = locations.slice().sort().reverse()
console.log(reverseAlphabeticalOrder)
console.log("original")
console.log(locations)
console.log("reverse")
reverse = locations.slice().reverse()
console.log(reverse)
console.log("original")
console.log(locations)
console.log("changed order")
console.log(locations.reverse())
console.log("now order is changed")
console.log(locations)
console.log(locations.reverse())
console.log("back to original order")
console.log(locations)
console.log("alphabetically sorted and its order has been changed")
locations.sort()
console.log(locations)
console.log("alphabetically reverse sorted and its order has been changed")
locations.sort().reverse()
console.log(locations)